# Generated by Django 6.1 on 2026-09-02 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='batch_id',
            field=models.CharField(default='FSD_Python_64', max_length=30),
            preserve_default=False,
        ),
    ]
